name: Deploy Lambda Function
on:
  push:
    paths:
      - 'src/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip tool
        users: montudor/action-zip@v1
      - name: Create Zip file for Lambda function
        run: cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@latest
        with:
            args: "lambda update-function-code \
            "