name: FastAPI CI/CD

on:
  push:
    branches:
      - main

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Python Virtual Environment
        run: pip3 install virtualenv

      - name: Activate Virtual Environment and Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Create archive of dependencies
        run: |
          cd venv/lib/python3.12/site-packages
          zip -r9 ../../../../api.zip .

      - name: Add API files to Zip file
        run: |
          zip -g api.zip -r api

      - name: Upload zip file artifact
        uses: actions/upload-artifact@v4
        with:
          name: api
          path: api.zip

  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Download Lambda api.zip artifact
        uses: actions/download-artifact@v4
        with:
          name: api
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
  
      - name: Upload to S3
        run: aws s3 cp api.zip s3://fastapi-mooccubex/api.zip
  
      - name: Verify S3 Upload
        run: aws s3 ls s3://fastapi-mooccubex/api.zip
  
      - name: Deploy new Lambda
        run: |
          for i in {1..3}; do
            aws lambda update-function-code \
              --function-name fastapi-auth \
              --s3-bucket fastapi-mooccubex \
              --s3-key api.zip && break || sleep 10 \
              --environment "Variables={SECRET_KEY=${{ secrets.SECRET_KEY }}, AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}, AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}}"
          done
